### ISSUE TITLE
Reload doesn't work when blacklist does not exist

### ISSUE THREAD

**Issue by bstoney** [auchenberg/css-reloader-chrome#22] opened 2016-11-04 23:16 UTC
If the settings have never been edited the blacklist is undefined and every Reload CSS attempt fails. An error is reported in the Developer Tool console:

```
Error in event handler for extension.onRequest: TypeError: Cannot read property 'length' of undefined
    at domainIsBlacklisted (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:27:48)
    at reload (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:15:18)
    at onExtensionRequest (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:51:13)
```

**Comment by mborn319** [comment] 2016-11-06 00:22
Hi @bstoney , thanks for the bug report! I believe this is a duplicate of #21 , which is fixed but not yet deployed to the Chrome store.
@auchenberg hate to keep bugging you, but we need [my latest commit](https://github.com/auchenberg/css-reloader-chrome/commit/805ec7ea9b45e1738a63a71b21bc9716611c0ea5) pushed to the Chrome store.

**Comment by auchenberg** [comment] 2016-11-06 03:19
@mborn319 Version 1.1.7 has been tagged and released.

**Closed by auchenberg** 2016-11-06 03:19 UTC
