### ISSUE TITLE
dont work everywhere

### ISSUE THREAD

**Issue by ruslan-vyaznikov** [auchenberg/css-reloader-chrome#21] opened 2016-10-31 07:17 UTC
this is message in console 
Error in event handler for extension.onRequest: TypeError: Cannot read property 'length' of undefined
    at domainIsBlacklisted (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:27:48)
    at reload (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:15:18)
    at onExtensionRequest (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:51:13)

Chrome/54.0.2840.71 

This happend all the time when i try to reload my css in the project.

**Comment by mborn319** [comment] 2016-10-31 17:59
Looks like the new "blacklist" setting isn't set by default. I will take care of this.

**Comment by mborn319** [comment] 2016-10-31 18:00
I'm just realizing this is a duplicate of #20 , and #20 is not what I originally thought it was.

**Comment by mborn319** [comment] 2016-11-01 03:07
Thanks for the detailed error message @ruslan-vyaznikov ! Next we need an updated version in the Google Chrome store... @auchenberg .

**Comment by auchenberg** [comment] 2016-11-01 03:18
Version 1.1.6 has been pushed to the Chrome store, @mborn319, @ruslan-vyaznikov

**Comment by senff** [comment] 2016-11-01 15:31
I have 1.1.6 of the extension on my Chrome 54.0.2840.71 and I'm still getting this error. :(

```
Error in event handler for extension.onRequest: TypeError: Cannot read property 'length' of undefined
    at domainIsBlacklisted (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:27:48)
    at reload (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:15:18)
    at onExtensionRequest (chrome-extension://dnfpcpfijpdhabaoieccoclghgplmpbd/cssreloader.content.js:51:13)
```

**Comment by mborn319** [comment] 2016-11-02 03:21
Thanks @senff . This should be all set. I didn't realize the settings were saved in localStorage, and needed to be updated if they didn't have the new `blacklist` field.

**Closed** 2016-11-02 03:21 UTC

**Comment by bstoney** [comment] 2016-11-06 21:43
@mborn319 this still isn't working. The blacklist setting check needs to be in parentheses i.e. `!("blacklist" in settings)`

**Comment by auchenberg** [comment] 2016-11-06 23:39
Fixed  in https://github.com/auchenberg/css-reloader-chrome/commit/35cb5bae61a727ad921fcde5db7efd6dc8d0ce9e

**Comment by mborn319** [comment] 2016-11-07 03:19
Oh, my goodness. Thanks guys.

**Comment by bstoney** [comment] 2016-11-07 15:01
All good, thanks heaps.
