### ISSUE TITLE
keyIdentifier deprecation in Chrome 53

### ISSUE THREAD

**Issue by csulok** [auchenberg/css-reloader-chrome#18] opened 2016-08-31 08:47 UTC
New Chrome version started showing this warning in developer tools when cssreloader is active. Not exactly sure what functionality will break when 53 lands, but it would be worth a look and updating the extension.

**[cssreloader.content.js:24](https://github.com/auchenberg/css-reloader-chrome/blob/master/cssreloader.content.js#L24)** 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by mborn319** [comment] 2016-10-01 14:58
[Duplicate] Duplicate of #16 .
[Fixed] Fixed by Issue #17 .
Can we mark this complete?

**Closed** 2016-10-02 00:21 UTC
